#!/bin/bash
set -e

PROJECT_ROOT="$(cd "$(dirname "$0")" && pwd)"
SAVE_PATH="${SAVE_PATH:-$PROJECT_ROOT/saves/test_map.zip}"
RCON_PORT="${RCON_PORT:-27015}"
RCON_PASSWORD="${RCON_PASSWORD:-factorio}"
GAME_PORT="${GAME_PORT:-34197}"

# Find Factorio binary
if [ -n "$FACTORIO_BIN" ]; then
    : # use env var
elif command -v factorio &>/dev/null; then
    FACTORIO_BIN="$(command -v factorio)"
elif [ -f "$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio" ]; then
    FACTORIO_BIN="$HOME/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio"
elif [ -f "$HOME/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio" ]; then
    FACTORIO_BIN="$HOME/.local/share/Steam/steamapps/common/Factorio/bin/x64/factorio"
elif [ -f "$HOME/Library/Application Support/Steam/steamapps/common/Factorio/bin/x64/factorio" ]; then
    FACTORIO_BIN="$HOME/Library/Application Support/Steam/steamapps/common/Factorio/bin/x64/factorio"
else
    echo "ERROR: Factorio binary not found. Set FACTORIO_BIN=/path/to/factorio"
    exit 1
fi

# Derive Factorio data path from binary location (for read-data)
FACTORIO_DATA="$(dirname "$(dirname "$(dirname "$FACTORIO_BIN")")")/data"

# Generate server config if missing or stale
CONFIG_DIR="$PROJECT_ROOT/.factorio-server"
CONFIG_FILE="$CONFIG_DIR/config.ini"
WRITE_DATA="$PROJECT_ROOT/.factorio-server-data"

mkdir -p "$CONFIG_DIR" "$WRITE_DATA/mods"

# Always regenerate config (paths may change between machines)
cat > "$CONFIG_FILE" << EOF
; Auto-generated by start-server.sh — do not edit by hand
[path]
read-data=$FACTORIO_DATA
write-data=$WRITE_DATA

[other]
check-updates=false
EOF

# Ensure mod is symlinked/copied into server mods
MOD_SRC="$PROJECT_ROOT/mod/claude-interface"
MOD_DST="$WRITE_DATA/mods/claude-interface"
if [ ! -e "$MOD_DST" ]; then
    # Try symlink first, fall back to copy (Flatpak can't follow symlinks)
    ln -s "$MOD_SRC" "$MOD_DST" 2>/dev/null || cp -r "$MOD_SRC" "$MOD_DST"
fi

# Handle --fresh flag: recreate save from scratch
if [ "$1" = "--fresh" ]; then
    echo "Creating fresh save..."
    mkdir -p "$PROJECT_ROOT/saves"
    "$FACTORIO_BIN" \
        --config "$CONFIG_FILE" \
        --create "$SAVE_PATH" \
        --map-gen-settings "$PROJECT_ROOT/configs/map-gen.json"
    echo "Fresh save created at $SAVE_PATH"
fi

if [ ! -f "$SAVE_PATH" ]; then
    echo "No save found at $SAVE_PATH — creating one..."
    mkdir -p "$PROJECT_ROOT/saves"
    "$FACTORIO_BIN" \
        --config "$CONFIG_FILE" \
        --create "$SAVE_PATH" \
        --map-gen-settings "$PROJECT_ROOT/configs/map-gen.json"
fi

if pgrep -f "factorio.*--start-server" > /dev/null; then
    echo "Server already running. Use stop-server.sh first."
    exit 1
fi

mkdir -p "$PROJECT_ROOT/logs"

echo "Starting Factorio headless server..."
echo "  RCON: localhost:$RCON_PORT"
echo "  Game: localhost:$GAME_PORT"
echo "  Save: $SAVE_PATH"

STDIN_FIFO="$PROJECT_ROOT/logs/server.stdin"
STDIN_KEEPER_PID_FILE="$PROJECT_ROOT/logs/server.stdin.pid"
rm -f "$STDIN_FIFO" "$STDIN_KEEPER_PID_FILE"
mkfifo "$STDIN_FIFO"

# Factorio's headless server exits when stdin reaches EOF. Keep a silent writer
# attached to a FIFO, and detach both processes from the launcher shell so
# non-interactive invocations do not SIGHUP the server immediately after the
# RCON readiness check passes.
nohup tail -f /dev/null > "$STDIN_FIFO" 2>/dev/null &
STDIN_KEEPER_PID=$!
echo "$STDIN_KEEPER_PID" > "$STDIN_KEEPER_PID_FILE"

setsid "$FACTORIO_BIN" \
    --config "$CONFIG_FILE" \
    --start-server "$SAVE_PATH" \
    --rcon-port "$RCON_PORT" \
    --rcon-password "$RCON_PASSWORD" \
    --port "$GAME_PORT" \
    --server-settings "$PROJECT_ROOT/configs/server.json" \
    < "$STDIN_FIFO" \
    > "$PROJECT_ROOT/logs/server.log" 2>&1 &

SERVER_PID=$!
echo "$SERVER_PID" > "$PROJECT_ROOT/logs/server.pid"
echo "Server PID: $SERVER_PID"

# Wait for RCON to become available
FACTORIOCTL="${PROJECT_ROOT}/../target/release/factorioctl"
if [ -x "$FACTORIOCTL" ]; then
    echo -n "Waiting for RCON..."
    for i in $(seq 1 30); do
        if "$FACTORIOCTL" --port "$RCON_PORT" --password "$RCON_PASSWORD" get tick 2>/dev/null; then
            echo ""
            echo "Server ready!"
            exit 0
        fi
        sleep 1
        echo -n "."
    done
    echo ""
    echo "ERROR: Server did not become ready. Check $PROJECT_ROOT/logs/server.log"
    kill "$SERVER_PID" "$STDIN_KEEPER_PID" 2>/dev/null || true
    rm -f "$STDIN_FIFO" "$STDIN_KEEPER_PID_FILE" "$PROJECT_ROOT/logs/server.pid"
    exit 1
else
    echo "factorioctl not found — skipping RCON check. Wait a few seconds, then connect."
    echo "(Build it: cd factorioctl && cargo build --release)"
fi
